site_name: Gaurav
  
theme:
  name: material
  features:
    - content.code.copy
    - search.suggest
    - navigation.tabs
    - navigation.indexes
  palette:
    primary: black

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://github.com/gauravreddy08
    - icon: fontawesome/brands/github 
      link: https://github.com/gauravreddy08
    

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg