site_name: Gaurav
site_url: https://gauravreddy08.github.io/portfolio/

theme:
  icon:
    annotation: material/plus-circle
  name: material
  features:
    - content.code.copy
    - search.suggest
    - navigation.tabs
    - navigation.indexes
  palette:
    primary: black

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://github.com/gauravreddy08
    - icon: fontawesome/brands/github 
      link: https://github.com/gauravreddy08
  analytics:
    provider: google
    property: G-YMMLD1CVDS
  

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js